import unittest

from basic_exponentials import basic_exponential_test
from variable_exponentials import variable_exponential_test
from exponential_exponentials import exponential_exponential_test
from fraction_exponentials import fraction_exponential_test
from complex_number_exponentials import complex_number_exponential_test
from logarithm_exponentials import logarithm_exponential_test
from chain_exponentials import chain_exponential_test
from product_exponentials import product_exponential_test


if __name__ == "__main__":
    unittest.main()
